title: GatewayConfig
type: object
required:
  - ipv4
  - ipv6
  - performance
properties:
  performance:
    type: boolean
    description: Enable / disable performance mode.  If enabled, gateway can use much more RAM and CPU.
  ipv4:
    type: boolean
    description: Allow / disallow traffic to be routed via IPv4.
  ipv6:
    type: boolean
    description: Allow / disallow traffic to be routed via IPv6.
