title: SourceAwsEbs
type: object
description: >
  An AWS EBS volume source. Defines how to authenticate to AWS and which EBS
  volume to attach.
required:
  - type
  - details
properties:
  type:
    type: string
    enum:
      - aws-ebs
  details:
    type: object
    required:
      - integration_id
      - volume
    properties:
      integration_id:
        description: >
          The ID of an AWS EBS integration for authentication.
        $ref: ../../../../ID.yml
      volume:
        $ref: "./SourceAwsEbsRef.yml"
