title: EnvironmentDeploymentReinstateStep
type: object
description: |
  Reinstates a previously deprecated deployment within an environment,
  restoring it to active status and allowing it to receive traffic again.
required:
  - action
  - details
properties:
  identifier:
    type: string
    description: An identifier for the step.
  options:
    type: object
    properties:
      skip:
        type: boolean
  action:
    type: string
    description: The action that the step takes.
    enum:
      - environment.deployment.reinstate
  details:
    type: object
    required:
      - environment
    properties:
      environment:
        $ref: ../FluidIdentifier.yml
      tag:
        type:
          - string
          - "null"
      version:
        type:
          - string
          - "null"
