type: object
title: ServerTelemetrySnapshot
description: A single frame of server telemetry.
required:
  - generated
  - system
  - cpu
  - memory
  - network
  - disk
  - processes
properties:
  generated:
    $ref: "../../../DateTime.yml"
    description: The timestamp at which this telemetry snapshot was generated.
  system:
    description: General system telemetry. Null when system telemetry is unavailable.
    oneOf:
      - $ref: ./ServerTelemetrySystem.yml
      - type: "null"
  cpu:
    description: CPU telemetry for this snapshot. Null when CPU telemetry is unavailable.
    oneOf:
      - $ref: ./ServerTelemetryCpu.yml
      - type: "null"
  memory:
    description: Memory telemetry for this snapshot. Null when memory telemetry is unavailable.
    oneOf:
      - $ref: ./ServerTelemetryMemory.yml
      - type: "null"
  network:
    description: Network telemetry for this snapshot. Null when network telemetry is unavailable.
    oneOf:
      - $ref: ./ServerTelemetryNetwork.yml
      - type: "null"
  disk:
    description: Disk telemetry for this snapshot. Null when disk telemetry is unavailable.
    oneOf:
      - $ref: ./ServerTelemetryDisk.yml
      - type: "null"
  processes:
    description: Process telemetry for this snapshot. Null when process telemetry is unavailable.
    oneOf:
      - $ref: ./ServerTelemetryProcesses.yml
      - type: "null"
