title: EnvironmentDeploymentStopAction
type: object
description: |
  Stops a specific deployment within an environment. Requires a deployment
  object identifying the tag and version to stop.
required:
  - action
  - contents
properties:
  action:
    type: string
    enum:
      - deployment.stop
  contents:
    type: object
    required:
      - deployment
    properties:
      deployment:
        description: The selector for which deployment to stop.
        oneOf:
          - type: object
            properties:
              version:
                description: Targets the deployment with this exact version.
                $ref: ../../Version.yml
          - type: object
            properties:
              tag:
                description: Targets the deployment with this exact tag applied to it.
                type: string
